name = "PerfusionImaging"
uuid = "187119c3-f0c9-4846-bd2a-6fdb8a2d7639"
authors = ["Dale Black <djblack@uci.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
DICOM = "a26e6606-dd52-5f6a-a97f-4f611373d757"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DICOM = "0.10"
LsqFit = "0.15"
Statistics = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
